const initialProducts = [
  {
    name: 'Vintage Washed Black Embroidery Cap',
    slug: 'vintage-washed-black-embroidery-cap',
    category: 'Caps',
    brand: 'URBAN FIT',
    collectionName: 'Vintage Streetwear 2026',
    description: 'Premium vintage washed cotton baseball cap featuring high-density 3D front embroidery, adjustable brass buckle strap, and breathable 6-panel eyelet construction.',
    price: 300,
    discountPrice: 300,
    sizes: [{ size: 'Free Size', stock: 100 }],
    colors: [{ name: 'Washed Black', hex: '#222225' }],
    stock: 100,
    images: ['/uploads/cap1.png', '/uploads/cap2.png', '/uploads/cap3.png', '/uploads/cap4.png', '/uploads/cap5.png'],
    thumbnail: '/uploads/cap1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.9
  },
  {
    name: 'Vintage Paisley Printed Black Cotton Bandana',
    slug: 'vintage-paisley-printed-black-cotton-bandana',
    category: 'Accessories',
    brand: 'URBAN FIT',
    collectionName: 'Vintage Streetwear 2026',
    description: '100% premium woven cotton bandana featuring classic black and white paisley border graphics.',
    price: 250,
    discountPrice: 250,
    sizes: [{ size: 'Free Size', stock: 150 }],
    colors: [{ name: 'Paisley Black / White', hex: '#111115' }],
    stock: 150,
    images: ['/uploads/bandana1.png', '/uploads/bandana2.png', '/uploads/bandana3.png', '/uploads/bandana4.png', '/uploads/bandana5.png'],
    thumbnail: '/uploads/bandana1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.92
  },
  {
    name: 'Masato Kawajo SECND SLF Oversized Long Sleeve',
    slug: 'masato-kawajo-secnd-slf-oversized-long-sleeve',
    category: 'Shirts',
    brand: 'URBAN FIT',
    collectionName: 'Contemporary Streetwear 2026',
    description: 'Heavyweight 320 GSM French terry cotton long-sleeve tee featuring custom electric blue Masato Kawajo SECND SLF shield graphics.',
    price: 900,
    discountPrice: 900,
    sizes: [{ size: 'S', stock: 20 }, { size: 'M', stock: 40 }, { size: 'L', stock: 40 }, { size: 'XL', stock: 20 }],
    colors: [{ name: 'Jet Black / Electric Blue', hex: '#0a0a0c' }],
    stock: 120,
    images: ['/uploads/shirt1.png', '/uploads/shirt2.png', '/uploads/shirt3.png', '/uploads/shirt4.png', '/uploads/shirt5.png'],
    thumbnail: '/uploads/shirt1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 5.0
  },
  {
    name: 'Vintage Washed Black Wide-Leg Chain & Bandana Jeans',
    slug: 'vintage-washed-black-wide-leg-chain-bandana-jeans',
    category: 'Jeans',
    brand: 'URBAN FIT',
    collectionName: 'Vintage Streetwear 2026',
    description: 'Heavyweight washed denim wide-leg jeans featuring detachable multi-layer silver pocket chains and paisley bandana accent.',
    price: 1200,
    discountPrice: 1200,
    sizes: [{ size: '28', stock: 25 }, { size: '30', stock: 35 }, { size: '32', stock: 35 }, { size: '34', stock: 25 }],
    colors: [{ name: 'Washed Charcoal Black', hex: '#1c1c20' }],
    stock: 150,
    images: ['/uploads/pants1.png', '/uploads/pants2.png', '/uploads/pants3.png', '/uploads/pants4.png', '/uploads/pants5.png'],
    thumbnail: '/uploads/pants1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.95
  },
  {
    name: 'Puma Speedcat Suede Black & Silver Formstrip Sneakers',
    slug: 'puma-speedcat-suede-black-silver-formstrip-sneakers',
    category: 'Shoes',
    brand: 'PUMA x URBAN FIT',
    collectionName: 'Motorsport Streetwear 2026',
    description: 'Iconic low-profile suede sneakers featuring metallic silver formstrip overlays and embroidered white cat emblem.',
    price: 1800,
    discountPrice: 1800,
    sizes: [{ size: '7', stock: 25 }, { size: '8', stock: 35 }, { size: '9', stock: 35 }, { size: '10', stock: 25 }],
    colors: [{ name: 'Suede Black / Metallic Silver', hex: '#111116' }],
    stock: 100,
    images: ['/uploads/shoes1.png', '/uploads/shoes2.png', '/uploads/shoes3.png', '/uploads/shoes4.png', '/uploads/shoes5.png'],
    thumbnail: '/uploads/shoes1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.98
  },
  {
    name: 'Monochrome Abstract Graphic Printed Shirt',
    slug: 'monochrome-abstract-graphic-printed-shirt',
    category: 'Shirts',
    brand: 'URBAN FIT',
    collectionName: 'Contemporary Streetwear 2026',
    description: 'Premium woven cotton full-sleeve button-down shirt featuring an eye-catching abstract monochrome doodle graphic pattern.',
    price: 700,
    discountPrice: 700,
    sizes: [{ size: 'S', stock: 25 }, { size: 'M', stock: 50 }, { size: 'L', stock: 50 }, { size: 'XL', stock: 25 }],
    colors: [{ name: 'Monochrome Pattern Black / White', hex: '#111115' }],
    stock: 150,
    images: ['/uploads/pattern_shirt1.png', '/uploads/pattern_shirt2.png', '/uploads/pattern_shirt3.png', '/uploads/pattern_shirt4.png', '/uploads/pattern_shirt5.png'],
    thumbnail: '/uploads/pattern_shirt1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.96
  },
  {
    name: 'Grey Collar "Live to Love" Quarter-Zip Polo T-Shirt',
    slug: 'grey-collar-live-to-love-quarter-zip-polo-t-shirt',
    category: 'T-Shirts',
    brand: 'URBAN FIT',
    collectionName: 'Contemporary Streetwear 2026',
    description: 'Vintage heather grey quarter-zip collar polo t-shirt featuring contrast white sleeve block bands and "Live to Love" calligraphy graphic.',
    price: 600,
    discountPrice: 600,
    sizes: [{ size: 'S', stock: 25 }, { size: 'M', stock: 50 }, { size: 'L', stock: 50 }, { size: 'XL', stock: 25 }],
    colors: [{ name: 'Heather Grey / White', hex: '#888890' }],
    stock: 150,
    images: ['/uploads/grey_polo1.png', '/uploads/grey_polo2.png', '/uploads/grey_polo3.png', '/uploads/grey_polo4.png', '/uploads/grey_polo5.png'],
    thumbnail: '/uploads/grey_polo1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.97
  },
  {
    name: 'Pleated Light Grey Tailored Formal Trousers',
    slug: 'pleated-light-grey-tailored-formal-trousers',
    category: 'Pants',
    brand: 'URBAN FIT',
    collectionName: 'Vintage Streetwear 2026',
    description: 'Sophisticated light grey double-pleated tailored trousers featuring a mid-rise fit and slant side pockets.',
    price: 900,
    discountPrice: 900,
    sizes: [{ size: '28', stock: 20 }, { size: '30', stock: 35 }, { size: '32', stock: 35 }, { size: '34', stock: 25 }],
    colors: [{ name: 'Light Grey', hex: '#b0b0b8' }],
    stock: 130,
    images: ['/uploads/grey_trousers1.png', '/uploads/grey_trousers2.png', '/uploads/grey_trousers3.png', '/uploads/grey_trousers4.png', '/uploads/grey_trousers5.png'],
    thumbnail: '/uploads/grey_trousers1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.95
  },
  {
    name: 'Nike Victori One Black & White Swoosh Slides',
    slug: 'nike-victori-one-black-white-swoosh-slides',
    category: 'Shoes',
    brand: 'NIKE x URBAN FIT',
    collectionName: 'Motorsport Streetwear 2026',
    description: 'Iconic lightweight black sport slides featuring a soft padded strap with prominent white Nike Swoosh branding.',
    price: 1800,
    discountPrice: 1800,
    sizes: [{ size: '7', stock: 25 }, { size: '8', stock: 35 }, { size: '9', stock: 35 }, { size: '10', stock: 25 }],
    colors: [{ name: 'Matte Black / White', hex: '#111115' }],
    stock: 150,
    images: ['/uploads/nike_slides1.png', '/uploads/nike_slides2.png', '/uploads/nike_slides3.png', '/uploads/nike_slides4.png', '/uploads/nike_slides5.png'],
    thumbnail: '/uploads/nike_slides1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.98
  },
  {
    name: 'Nike Layered Dusty Pink & 3-Stripe Black Sleeve Shirt',
    slug: 'nike-layered-dusty-pink-3-stripe-black-sleeve-shirt',
    category: 'Shirts',
    brand: 'NIKE x URBAN FIT',
    collectionName: 'Contemporary Streetwear 2026',
    description: 'Modern streetwear layered shirt featuring a dusty pink short-sleeve button-down outer layer over attached black 3-stripe long sleeves.',
    price: 900,
    discountPrice: 900,
    sizes: [{ size: 'S', stock: 20 }, { size: 'M', stock: 40 }, { size: 'L', stock: 40 }, { size: 'XL', stock: 20 }],
    colors: [{ name: 'Dusty Pink / Black', hex: '#b88494' }],
    stock: 120,
    images: ['/uploads/pink_layered_shirt1.png', '/uploads/pink_layered_shirt2.png', '/uploads/pink_layered_shirt3.png', '/uploads/pink_layered_shirt4.png', '/uploads/pink_layered_shirt5.png'],
    thumbnail: '/uploads/pink_layered_shirt1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.97
  },
  {
    name: 'Minimalist Jet Black Oversized Long Sleeve Shirt',
    slug: 'minimalist-jet-black-oversized-long-sleeve-shirt',
    category: 'Shirts',
    brand: 'URBAN FIT',
    collectionName: 'Vintage Streetwear 2026',
    description: 'Sleek jet black tailored long-sleeve camp collar shirt featuring a minimalist relaxed silhouette and button-down front.',
    price: 800,
    discountPrice: 800,
    sizes: [{ size: 'S', stock: 25 }, { size: 'M', stock: 50 }, { size: 'L', stock: 50 }, { size: 'XL', stock: 25 }],
    colors: [{ name: 'Jet Black', hex: '#0a0a0d' }],
    stock: 150,
    images: ['/uploads/black_camp_shirt1.png', '/uploads/black_camp_shirt2.png', '/uploads/black_camp_shirt3.png', '/uploads/black_camp_shirt4.png', '/uploads/black_camp_shirt5.png'],
    thumbnail: '/uploads/black_camp_shirt1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.96
  },
  {
    name: 'Pleated Classic Beige Tailored Trousers',
    slug: 'pleated-classic-beige-tailored-trousers',
    category: 'Pants',
    brand: 'URBAN FIT',
    collectionName: 'Vintage Streetwear 2026',
    description: 'Elegant classic beige double-pleated tailored trousers featuring a mid-rise fit and slant front pockets.',
    price: 800,
    discountPrice: 800,
    sizes: [{ size: '28', stock: 20 }, { size: '30', stock: 35 }, { size: '32', stock: 35 }, { size: '34', stock: 25 }],
    colors: [{ name: 'Classic Beige', hex: '#e3d7c5' }],
    stock: 130,
    images: ['/uploads/beige_trousers1.png', '/uploads/beige_trousers2.png', '/uploads/beige_trousers3.png', '/uploads/beige_trousers4.png', '/uploads/beige_trousers5.png'],
    thumbnail: '/uploads/beige_trousers1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.95
  },
  {
    name: 'Vintage Acid Washed Grey Wide-Leg Straight Jeans',
    slug: 'vintage-acid-washed-grey-wide-leg-straight-jeans',
    category: 'Jeans',
    brand: 'URBAN FIT',
    collectionName: 'Vintage Streetwear 2026',
    description: 'Heavyweight premium acid washed grey denim jeans featuring a wide-leg straight silhouette and traditional 5-pocket construction.',
    price: 1100,
    discountPrice: 1100,
    sizes: [{ size: '28', stock: 20 }, { size: '30', stock: 35 }, { size: '32', stock: 35 }, { size: '34', stock: 25 }],
    colors: [{ name: 'Acid Washed Grey', hex: '#6b6c70' }],
    stock: 130,
    images: ['/uploads/grey_jeans1.png', '/uploads/grey_jeans2.png', '/uploads/grey_jeans3.png', '/uploads/grey_jeans4.png', '/uploads/grey_jeans5.png'],
    thumbnail: '/uploads/grey_jeans1.png',
    isFeatured: true,
    isNewArrival: true,
    rating: 4.97
  }
];

module.exports = initialProducts;
